# Generated by Django 3.1.14 on 2022-04-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_auto_20220418_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='next_evolution',
            new_name='previous_evolution',
        ),
    ]
