# Generated by Django 3.1.14 on 2022-04-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20220420_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonentity',
            name='pokemon_element_type',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_element_type',
            field=models.ManyToManyField(to='pokemon_entities.PokemonElementType'),
        ),
    ]
